move selecting appropriate codes to its own sections
opensafely-core/opencodelists pull request #1967
Opened 2024-05-24 09:33 UTC by LFISHER7

2024-05-24 09:41 UTC, brianmackenna requested changes

2024-06-03 15:51 UTC, chrisjwood16 commented on userdocs/views.py
> +    "selecting-appropriate-codes",
This looks great to me!

2024-07-09 09:34 UTC, chrisjwood16 approved these changes

2024-07-09 09:34 UTC, chrisjwood16 approved these changes

2024-07-09 09:38 UTC, merged

2024-07-09 16:21 UTC, brianmackenna commented
boom! 

You should share on users channel to promote!